Modify workflow strategy

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -39,13 +39,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        problem: ["6.10.1", "6.10.2", "6.10.3", "6.10.4", "6.20.1", "6.20.2", "6.20.3", "6.20.4", "6.5.1", "6.5.2", "6.5.3", "6.5.4",
-          "10.10.1", "10.10.2", "10.10.3", "10.10.4", "10.20.1", "10.20.2", "10.20.3", "10.20.4", "10.5.1", "10.5.2", "10.5.3", "10.5.4",
-          "12.10.1", "12.10.2", "12.10.3", "12.10.4", "12.20.1", "12.20.2", "12.20.3", "12.20.4", "12.5.1", "12.5.2", "12.5.3", "12.5.4",
-          "20.10.1", "20.10.2", "20.10.3", "20.10.4", "20.20.1", "20.20.2", "20.20.3", "20.20.4", "20.5.1", "20.5.2", "20.5.3", "20.5.4",
-          "50.10.1", "50.10.2", "50.10.3", "50.10.4", "50.20.1", "50.20.2", "50.20.3", "50.20.4", "50.30.1", "50.30.2", "50.30.3", "50.30.4", "50.40.1", "50.40.2", "50.40.3", "50.40.4",
-          "100.10.1", "100.10.2", "100.10.3", "100.10.4", "100.20.1", "100.20.2", "100.20.3", "100.20.4", "100.30.1", "100.30.2", "100.30.3", "100.30.4", "100.40.1", "100.40.2", "100.40.3", "100.40.4"]
-        steps: [0, 1]
+        steps: [0, 1, 2, 3, 4]
 
     steps:
       - name: Checkout repository
@@ -67,14 +61,16 @@ jobs:
           exitcode=0
           set +e
           let begin=5*${{ matrix.steps }}+1
-          let end=$begin+4
+          let end=$begin+1
 
-          report_error() {
-            this_exitcode=$?
+          execute() {
+            command=$1
+            echo "Running \"$command\""
+            $command
 
-            if [ $this_exitcode -ne 0 ]
-            then
-              echo "::warning::Exit code $this_exitcode at run #$i"
+            status=$?
+            if [ $status -ne 0 ]; then
+              echo "::error::\"$command\" exit with status $status"
               exitcode=1
             fi
           }
@@ -82,8 +78,10 @@ jobs:
           for i in $(seq $begin $end)
           do
             echo "RUN #$i"
-            ./min-timespan-delivery run problems/data/${{ matrix.problem }}.txt --disable-logging --extra "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-            report_error
+            for path in $(find problems/data/*)
+            do
+              execute "./min-timespan-delivery run $path --disable-logging --extra ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+            done
           done
 
           exit $exitcode
@@ -92,7 +90,7 @@ jobs:
         uses: actions/upload-artifact@v4
         if: ${{ always() }}
         with:
-          name: output-${{ matrix.problem }}-${{ matrix.steps }}
+          name: output-${{ matrix.steps }}
           path: outputs/*
 
   summary:
