Run custom test 4

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -38,14 +38,17 @@ jobs:
           name: executable
           path: target/release/min-timespan-delivery
 
-  solve:
+  solve-500:
     name: Run algorithm
     runs-on: ubuntu-latest
     needs: build
     strategy:
       fail-fast: false
       matrix:
-        steps: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
+        problem: [500.10.1, 500.10.2, 500.10.3, 500.10.4, 500.20.1, 500.20.2, 500.20.3, 500.20.4, 500.30.1, 500.30.2, 500.30.3, 500.30.4, 500.40.1, 500.40.2, 500.40.3, 500.40.4]
+        adaptive-segments: [5, 7, 10]
+        adaptive-iterations: [50, 60, 70]
+        steps: [0]
 
     steps:
       - name: Checkout repository
@@ -85,13 +88,9 @@ jobs:
           for i in $(seq $begin $end)
           do
             echo "RUN #$i"
-            for path in $(find problems/data/*)
+            for path in $(find problems/data/${{ matrix.problem }}.txt)
             do
-              customers=$(grep -oP "(?<=customers )\d+" $path)
-              if [ $customers -lt 1000 ]
-              then
-                execute "./min-timespan-delivery run $path --disable-logging --extra ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-              fi
+              execute "./min-timespan-delivery run $path --max-elite-size 0 --adaptive-segments ${{ matrix.adaptive-segments }} --adaptive-iterations ${{ matrix.adaptive-iterations }} --disable-logging --extra ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
             done
           done
 
@@ -101,14 +100,79 @@ jobs:
         uses: actions/upload-artifact@v4
         if: ${{ always() }}
         with:
-          name: output-${{ matrix.steps }}
+          name: output-${{ matrix.problem }}-${{ matrix.adaptive-segments }}-${{ matrix.adaptive-iterations }}-${{ matrix.steps }}
+          path: outputs/*
+
+  solve-1000:
+    name: Run algorithm
+    runs-on: ubuntu-latest
+    needs: build
+    strategy:
+      fail-fast: false
+      matrix:
+        problem: [1000.10.1, 1000.10.2, 1000.10.3, 1000.10.4, 1000.20.1, 1000.20.2, 1000.20.3, 1000.20.4, 1000.30.1, 1000.30.2, 1000.30.3, 1000.30.4, 1000.40.1, 1000.40.2, 1000.40.3, 1000.40.4]
+        adaptive-segments: [5, 7, 10]
+        adaptive-iterations: [50, 60, 70]
+        steps: [0]
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - name: Download executable
+        uses: actions/download-artifact@v4
+        with:
+          name: executable
+          path: .
+
+      - name: Update permission
+        run: chmod +x min-timespan-delivery
+
+      - name: Run algorithm
+        run: |
+          exitcode=0
+          set +e
+          let begin=${{ matrix.steps }}+1
+          let end=$begin+0
+
+          execute() {
+            command=$1
+            echo "Running \"$command\""
+            $command
+
+            status=$?
+            if [ $status -ne 0 ]
+            then
+              echo "::error::\"$command\" exit with status $status"
+              exitcode=1
+            fi
+          }
+
+          for i in $(seq $begin $end)
+          do
+            echo "RUN #$i"
+            for path in $(find problems/data/${{ matrix.problem }}.txt)
+            do
+              execute "./min-timespan-delivery run $path --max-elite-size 0 --adaptive-segments ${{ matrix.adaptive-segments }} --adaptive-iterations ${{ matrix.adaptive-iterations }} --disable-logging --extra ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+            done
+          done
+
+          exit $exitcode
+
+      - name: Upload results
+        uses: actions/upload-artifact@v4
+        if: ${{ always() }}
+        with:
+          name: output-${{ matrix.problem }}-${{ matrix.adaptive-segments }}-${{ matrix.adaptive-iterations }}-${{ matrix.steps }}
           path: outputs/*
 
   summary:
     name: Summarize results
     runs-on: ubuntu-latest
     if: ${{ always() }}
-    needs: solve
+    needs: [solve-500, solve-1000]
 
     steps:
       - name: Checkout repository
