Fix job TLE

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -180,7 +180,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        steps: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
+        steps: [0, 1]
 
     steps:
       - name: Checkout repository
@@ -201,7 +201,7 @@ jobs:
         run: |
           exitcode=0
           set +e
-          let steps_per_run=1
+          let steps_per_run=5
           let begin=$steps_per_run*${{ matrix.steps }}+1
           let end=$begin+$steps_per_run-1
 
@@ -228,7 +228,7 @@ jobs:
 
               for trucks in $(seq 1 $(( (trucks_count + 1) / 2 )))
               do
-                if [ $customers -le 200 ]
+                if [ $customers -le 100 ]
                 then
                   execute "./min-timespan-delivery run $path --trucks-count $trucks --disable-logging --extra ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                 fi
@@ -243,6 +243,70 @@ jobs:
         if: ${{ always() }}
         with:
           name: output-${{ matrix.steps }}
+          path: outputs/*
+
+  solve-count-average:
+    name: Run algorithm
+    runs-on: ubuntu-latest
+    needs: build
+    strategy:
+      fail-fast: false
+      matrix:
+        trucks-count: [1, 2, 3, 4, 5]
+        steps: [0, 1, 2, 3, 4]
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
+        with:
+          submodules: recursive
+
+      - name: Download executable
+        uses: actions/download-artifact@v4
+        with:
+          name: executable
+          path: .
+
+      - name: Update permission
+        run: chmod +x min-timespan-delivery
+
+      - name: Run algorithm
+        run: |
+          exitcode=0
+          set +e
+          let steps_per_run=2
+          let begin=$steps_per_run*${{ matrix.steps }}+1
+          let end=$begin+$steps_per_run-1
+
+          execute() {
+            command=$1
+            echo "Running \"$command\""
+            $command
+
+            status=$?
+            if [ $status -ne 0 ]
+            then
+              echo "::error::\"$command\" exit with status $status"
+              exitcode=1
+            fi
+          }
+
+          for i in $(seq $begin $end)
+          do
+            echo "RUN #$i"
+            for path in $(find problems/data/200.*.txt)
+            do
+              execute "./min-timespan-delivery run $path --trucks-count ${{ matrix.trucks-count }} --disable-logging --extra ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+            done
+          done
+
+          exit $exitcode
+
+      - name: Upload results
+        uses: actions/upload-artifact@v4
+        if: ${{ always() }}
+        with:
+          name: output-${{ matrix.trucks-count }}-${{ matrix.steps }}
           path: outputs/*
 
   solve-count-medium:
@@ -340,7 +404,7 @@ jobs:
         run: |
           exitcode=0
           set +e
-          let steps_per_run=2
+          let steps_per_run=1
           let begin=$steps_per_run*${{ matrix.steps }}+1
           let end=$begin+$steps_per_run-1
 
@@ -379,7 +443,7 @@ jobs:
     name: Summarize results
     runs-on: ubuntu-latest
     if: ${{ always() }}
-    needs: [solve-capacity-small, solve-capacity-large, solve-count-small, solve-count-medium, solve-count-large]
+    needs: [solve-capacity-small, solve-capacity-large, solve-count-small, solve-count-average, solve-count-medium, solve-count-large]
 
     steps:
       - name: Checkout repository
