Run custom test 14

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -38,7 +38,142 @@ jobs:
           name: executable
           path: target/release/min-timespan-delivery
 
-  solve:
+  solve-capacity-small:
+    name: Run algorithm
+    runs-on: ubuntu-latest
+    needs: build
+    strategy:
+      fail-fast: false
+      matrix:
+        truck-capacity: [1400, 700, 350, 200, 100]
+        steps: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
+        with:
+          submodules: recursive
+
+      - name: Download executable
+        uses: actions/download-artifact@v4
+        with:
+          name: executable
+          path: .
+
+      - name: Update permission
+        run: chmod +x min-timespan-delivery
+
+      - name: Run algorithm
+        run: |
+          exitcode=0
+          set +e
+          let steps_per_run=1
+          let begin=$steps_per_run*${{ matrix.steps }}+1
+          let end=$begin+$steps_per_run-1
+
+          execute() {
+            command=$1
+            echo "Running \"$command\""
+            $command
+
+            status=$?
+            if [ $status -ne 0 ]
+            then
+              echo "::error::\"$command\" exit with status $status"
+              exitcode=1
+            fi
+          }
+
+          sed -i 's/1400/${{ matrix.truck-capacity }}/g' problems/config_parameter/truck_config.json
+          for i in $(seq $begin $end)
+          do
+            echo "RUN #$i"
+            for path in $(find problems/data/*)
+            do
+              customers=$(grep -oP "(?<=customers )\d+" $path)
+              if [ $customers -le 500 ]
+              then
+                execute "./min-timespan-delivery run $path --disable-logging --extra ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+              fi
+            done
+          done
+
+          exit $exitcode
+
+      - name: Upload results
+        uses: actions/upload-artifact@v4
+        if: ${{ always() }}
+        with:
+          name: output-${{ matrix.truck-capacity }}-${{ matrix.steps }}
+          path: outputs/*
+
+  solve-capacity-large:
+    name: Run algorithm
+    runs-on: ubuntu-latest
+    needs: build
+    strategy:
+      fail-fast: false
+      matrix:
+        problem: [1000.10.1, 1000.10.2, 1000.10.3, 1000.10.4, 1000.20.1, 1000.20.2, 1000.20.3, 1000.20.4, 1000.30.1, 1000.30.2, 1000.30.3, 1000.30.4, 1000.40.1, 1000.40.2, 1000.40.3, 1000.40.4]
+        truck-capacity: [1400, 700, 350, 200, 100]
+        steps: [0, 1, 2]
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
+        with:
+          submodules: recursive
+
+      - name: Download executable
+        uses: actions/download-artifact@v4
+        with:
+          name: executable
+          path: .
+
+      - name: Update permission
+        run: chmod +x min-timespan-delivery
+
+      - name: Run algorithm
+        run: |
+          exitcode=0
+          set +e
+          let steps_per_run=1
+          let begin=$steps_per_run*${{ matrix.steps }}+1
+          let end=$begin+$steps_per_run-1
+
+          execute() {
+            command=$1
+            echo "Running \"$command\""
+            $command
+
+            status=$?
+            if [ $status -ne 0 ]
+            then
+              echo "::error::\"$command\" exit with status $status"
+              exitcode=1
+            fi
+          }
+
+          sed -i 's/1400/${{ matrix.truck-capacity }}/g' problems/config_parameter/truck_config.json
+          for i in $(seq $begin $end)
+          do
+            echo "RUN #$i"
+            for path in $(find problems/data/${{ matrix.problem }}.txt)
+            do
+              execute "./min-timespan-delivery run $path --disable-logging --extra ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+            done
+          done
+
+          exit $exitcode
+
+      - name: Upload results
+        uses: actions/upload-artifact@v4
+        if: ${{ always() }}
+        with:
+          name: output-${{ matrix.problem }}-${{ matrix.truck-capacity }}-${{ matrix.steps }}
+          path: outputs/*
+
+  solve-count-small:
     name: Run algorithm
     runs-on: ubuntu-latest
     needs: build
@@ -89,10 +224,15 @@ jobs:
             for path in $(find problems/data/*)
             do
               customers=$(grep -oP "(?<=customers )\d+" $path)
-              if [ $customers -le 200 ]
-              then
-                execute "./min-timespan-delivery run $path --disable-logging --extra ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-              fi
+              trucks_count=$(grep -oP "(?<=trucks_count )\d+" $path)
+
+              for trucks in $(seq 1 $(( (trucks_count + 1) / 2 )))
+              do
+                if [ $customers -le 200 ]
+                then
+                  execute "./min-timespan-delivery run $path --trucks-count $trucks --disable-logging --extra ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+                fi
+              done
             done
           done
 
@@ -105,11 +245,140 @@ jobs:
           name: output-${{ matrix.steps }}
           path: outputs/*
 
+  solve-count-medium:
+    name: Run algorithm
+    runs-on: ubuntu-latest
+    needs: build
+    strategy:
+      fail-fast: false
+      matrix:
+        trucks-count: [1, 2, 3, 4, 5]
+        steps: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
+        with:
+          submodules: recursive
+
+      - name: Download executable
+        uses: actions/download-artifact@v4
+        with:
+          name: executable
+          path: .
+
+      - name: Update permission
+        run: chmod +x min-timespan-delivery
+
+      - name: Run algorithm
+        run: |
+          exitcode=0
+          set +e
+          let steps_per_run=2
+          let begin=$steps_per_run*${{ matrix.steps }}+1
+          let end=$begin+$steps_per_run-1
+
+          execute() {
+            command=$1
+            echo "Running \"$command\""
+            $command
+
+            status=$?
+            if [ $status -ne 0 ]
+            then
+              echo "::error::\"$command\" exit with status $status"
+              exitcode=1
+            fi
+          }
+
+          for i in $(seq $begin $end)
+          do
+            echo "RUN #$i"
+            for path in $(find problems/data/500.*.txt)
+            do
+              execute "./min-timespan-delivery run $path --trucks-count ${{ matrix.trucks-count }} --disable-logging --extra ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+            done
+          done
+
+          exit $exitcode
+
+      - name: Upload results
+        uses: actions/upload-artifact@v4
+        if: ${{ always() }}
+        with:
+          name: output-${{ matrix.trucks-count }}-${{ matrix.steps }}
+          path: outputs/*
+
+  solve-count-large:
+    name: Run algorithm
+    runs-on: ubuntu-latest
+    needs: build
+    strategy:
+      fail-fast: false
+      matrix:
+        problem: [1000.10.1, 1000.10.2, 1000.10.3, 1000.10.4, 1000.20.1, 1000.20.2, 1000.20.3, 1000.20.4, 1000.30.1, 1000.30.2, 1000.30.3, 1000.30.4, 1000.40.1, 1000.40.2, 1000.40.3, 1000.40.4]
+        trucks-count: [1, 2, 3, 4, 5, 6, 7, 8]
+        steps: [0, 1]
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
+        with:
+          submodules: recursive
+
+      - name: Download executable
+        uses: actions/download-artifact@v4
+        with:
+          name: executable
+          path: .
+
+      - name: Update permission
+        run: chmod +x min-timespan-delivery
+
+      - name: Run algorithm
+        run: |
+          exitcode=0
+          set +e
+          let steps_per_run=2
+          let begin=$steps_per_run*${{ matrix.steps }}+1
+          let end=$begin+$steps_per_run-1
+
+          execute() {
+            command=$1
+            echo "Running \"$command\""
+            $command
+
+            status=$?
+            if [ $status -ne 0 ]
+            then
+              echo "::error::\"$command\" exit with status $status"
+              exitcode=1
+            fi
+          }
+
+          for i in $(seq $begin $end)
+          do
+            echo "RUN #$i"
+            for path in $(find problems/data/${{ matrix.problem }}.txt)
+            do
+              execute "./min-timespan-delivery run $path --trucks-count ${{ matrix.trucks-count }} --disable-logging --extra ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+            done
+          done
+
+          exit $exitcode
+
+      - name: Upload results
+        uses: actions/upload-artifact@v4
+        if: ${{ always() }}
+        with:
+          name: output-${{ matrix.problem }}-${{ matrix.trucks-count }}-${{ matrix.steps }}
+          path: outputs/*
+
   summary:
     name: Summarize results
     runs-on: ubuntu-latest
     if: ${{ always() }}
-    needs: solve
+    needs: [solve-capacity-small, solve-capacity-large, solve-count-small, solve-count-medium, solve-count-large]
 
     steps:
       - name: Checkout repository
